import type { ICareerJob } from "./db/models/CareerJob";

/**
 * Curated job/internship listings for Indonesian students and fresh graduates.
 *
 * These are realistic, research-backed examples based on 2025–2026 Indonesian job
 * market data from LinkedIn, JobStreet, Glints, Kalibrr, Dealls, and web3.career.
 * They are NOT live scraped listings; they serve as EduSparq's curated career board.
 */

export const careerJobsSeed: Omit<ICareerJob, "_id">[] = [
  {
    title: "Data Analyst Intern",
    company: "Tokopedia",
    location: "Jakarta",
    workLocation: "hybrid",
    type: "internship",
    category: "Data & Analytics",
    skills: ["SQL", "Python", "Excel", "Tableau", "Data Storytelling"],
    salaryRange: "Rp 1.500.000 – 3.000.000/bulan",
    description:
      "Magang analisis data untuk mendukung tim bisnis memahami perilaku pengguna dan tren penjualan. Cocok untuk mahasiswa semester 5+ yang ingin membangun portofolio data.",
    requirements: [
      "Mahasiswa aktif minimal semester 5 jurusan Statistika, Matematika, Teknik Informatika, atau Sistem Informasi",
      "Memahami SQL dan Python dasar",
      "Mampu menyajikan insight dalam visualisasi sederhana",
    ],
    responsibilities: [
      "Mengolah data transaksi dan perilaku pengguna",
      "Membuat dashboard mingguan untuk tim bisnis",
      "Mendukung eksperimen produk dengan analisis hasil",
    ],
    sourceName: "LinkedIn / Glints",
    sourceUrl: "https://id.linkedin.com/jobs",
    postedAt: new Date("2026-06-15"),
    closesAt: new Date("2026-07-31"),
    active: true,
  },
  {
    title: "Junior Software Engineer",
    company: "Gojek",
    location: "Jakarta / Remote",
    workLocation: "hybrid",
    type: "entry",
    category: "Engineering",
    skills: ["Go", "JavaScript", "PostgreSQL", "Git", "REST API"],
    salaryRange: "Rp 8.000.000 – 12.000.000/bulan",
    description:
      "Posisi entry-level untuk engineer yang ingin membangun produk super-app dengan skala nasional. Dibuka untuk fresh graduate dan bootcamp graduate.",
    requirements: [
      "Fresh graduate atau pengalaman < 1 tahun di software engineering",
      "Memahami dasar algoritma, struktur data, dan database",
      "Memiliki portofolio proyek (GitHub) menjadi nilai tambah",
    ],
    responsibilities: [
      "Mengembangkan fitur backend/frontend sesuai tim yang dituju",
      "Menulis unit test dan dokumentasi teknis",
      "Berkolaborasi dengan product dan design",
    ],
    sourceName: "LinkedIn / JobStreet",
    sourceUrl: "https://id.linkedin.com/jobs",
    postedAt: new Date("2026-06-20"),
    closesAt: new Date("2026-08-15"),
    active: true,
  },
  {
    title: "AI/ML Engineer — Associate",
    company: "BRI",
    location: "Jakarta",
    workLocation: "onsite",
    type: "entry",
    category: "AI & Emerging Tech",
    skills: ["Python", "TensorFlow", "SQL", "Statistik", "Machine Learning"],
    salaryRange: "Rp 12.000.000 – 18.000.000/bulan",
    description:
      "Bergabung dengan tim data science bank BUMN untuk membangun model prediktif kredit, churn, dan fraud detection.",
    requirements: [
      "S1 Statistika, Matematika, Teknik Informatika, atau Data Science",
      "Pengalaman proyek ML dengan Python",
      "Memahami konsep supervised/unsupervised learning",
    ],
    responsibilities: [
      "Membangun dan men-deploy model ML untuk unit bisnis",
      "Melakukan feature engineering dan evaluasi model",
      "Mendokumentasikan eksperimen dan hasil model",
    ],
    sourceName: "JobStreet / LinkedIn",
    sourceUrl: "https://id.jobstreet.com/id/fresh-graduate-jobs",
    postedAt: new Date("2026-06-18"),
    closesAt: new Date("2026-07-30"),
    active: true,
  },
  {
    title: "Cybersecurity Operations Analyst",
    company: "Bank Mandiri",
    location: "Jakarta",
    workLocation: "onsite",
    type: "entry",
    category: "Security",
    skills: ["SIEM", "Network Security", "Incident Response", "CompTIA Security+", "Linux"],
    salaryRange: "Rp 10.000.000 – 15.000.000/bulan",
    description:
      "Posisi entry-level untuk memantau ancaman siber, menganalisis log keamanan, dan mendukung incident response.",
    requirements: [
      "S1 Teknik Informatika/Sistem Informasi atau sertifikasi security yang relevan",
      "Memahami dasar jaringan dan sistem operasi",
      "Bersedia shift dan belajar cepat",
    ],
    responsibilities: [
      "Memantau alert keamanan di SIEM",
      "Menganalisis malware dan aktivitas mencurigakan",
      "Membuat laporan insiden harian",
    ],
    sourceName: "Kalibrr / LinkedIn",
    sourceUrl: "https://www.kalibrr.com",
    postedAt: new Date("2026-06-10"),
    closesAt: new Date("2026-08-10"),
    active: true,
  },
  {
    title: "Cloud Engineer Intern",
    company: "Traveloka",
    location: "Jakarta / Remote",
    workLocation: "hybrid",
    type: "internship",
    category: "Infrastructure",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    salaryRange: "Rp 2.000.000 – 4.000.000/bulan",
    description:
      "Magang infrastruktur cloud untuk mendukung deployment, monitoring, dan otomasi platform Traveloka.",
    requirements: [
      "Mahasiswa semester 6+ Teknik Informatika/Sistem Informasi/Teknik Elektro",
      "Pernah menggunakan AWS/GCP/Azure akademik",
      "Familiar dengan Linux command line",
    ],
    responsibilities: [
      "Mendukung tim DevOps dalam deployment aplikasi",
      "Membuat dokumentasi arsitektur dan runbook",
      "Belajar dan mengimplementasikan Infrastructure as Code",
    ],
    sourceName: "Glints / LinkedIn",
    sourceUrl: "https://glints.com/id-id",
    postedAt: new Date("2026-06-22"),
    closesAt: new Date("2026-08-05"),
    active: true,
  },
  {
    title: "Digital Marketing Specialist",
    company: "Sirclo",
    location: "Jakarta / Remote",
    workLocation: "remote",
    type: "entry",
    category: "Marketing",
    skills: ["SEO", "Google Ads", "Meta Ads", "Marketing Analytics", "Content Writing"],
    salaryRange: "Rp 6.000.000 – 10.000.000/bulan",
    description:
      "Posisi entry-level untuk merancang dan mengelola kampanye digital e-commerce B2B dan B2C.",
    requirements: [
      "Fresh graduate jurusan Manajemen, Ilmu Komunikasi, atau Psikologi",
      "Memahami dasar SEO/SEM dan social media ads",
      "Kreatif dan data-driven",
    ],
    responsibilities: [
      "Menyusun kalender konten dan kampanye iklan",
      "Menganalisis performa campaign dan laporan mingguan",
      "Berkolaborasi dengan tim sales dan creative",
    ],
    sourceName: "Glints / JobStreet",
    sourceUrl: "https://id.jobstreet.com/id/fresh-graduate-jobs",
    postedAt: new Date("2026-06-12"),
    closesAt: new Date("2026-07-28"),
    active: true,
  },
  {
    title: "UI/UX Designer Intern",
    company: "Blibli",
    location: "Jakarta",
    workLocation: "hybrid",
    type: "internship",
    category: "Design",
    skills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems"],
    salaryRange: "Rp 1.800.000 – 3.500.000/bulan",
    description:
      "Magang desain produk digital untuk mendukung tim UI/UX dalam riset pengguna dan pembuatan prototype.",
    requirements: [
      "Mahasiswa semester 5+ Desain Komunikasi Visual, Desain Produk, atau HCI",
      "Portofolio UI/UX (case study minimal 1 proyek)",
      "Familiar dengan Figma",
    ],
    responsibilities: [
      "Membantu user research dan synthesize findings",
      "Membuat wireframe dan high-fidelity prototype",
      "Mendukung design review dan handoff ke engineer",
    ],
    sourceName: "LinkedIn / Glints",
    sourceUrl: "https://id.linkedin.com/jobs",
    postedAt: new Date("2026-06-25"),
    closesAt: new Date("2026-08-01"),
    active: true,
  },
  {
    title: "Associate Product Manager",
    company: "Sea Labs / Shopee",
    location: "Jakarta / Singapura",
    workLocation: "hybrid",
    type: "entry",
    category: "Product",
    skills: ["Product Thinking", "Agile", "Data Analysis", "User Research", "Communication"],
    salaryRange: "Rp 12.000.000 – 18.000.000/bulan",
    description:
      "Program entry-level untuk calon PM yang ingin belajar membangun produk tech di skala regional.",
    requirements: [
      "S1 Teknik Informatika, Manajemen, Sistem Informasi, atau sejenis",
      "Pengalaman organisasi/proyek produk menjadi nilai tambah",
      "Berpikir analitis dan komunikatif",
    ],
    responsibilities: [
      "Mendukung product manager dalam riset dan eksperimen",
      "Menulis PRD dan user stories",
      "Menganalisis metrik produk",
    ],
    sourceName: "LinkedIn / Glints",
    sourceUrl: "https://id.linkedin.com/jobs",
    postedAt: new Date("2026-06-08"),
    closesAt: new Date("2026-07-25"),
    active: true,
  },
  {
    title: "Business Development Representative",
    company: "Xendit",
    location: "Jakarta / Remote",
    workLocation: "hybrid",
    type: "entry",
    category: "Business",
    skills: ["Sales", "CRM", "Negotiation", "Market Research", "Communication"],
    salaryRange: "Rp 7.000.000 – 12.000.000/bulan + komisi",
    description:
      "Posisi entry-level untuk membangun pipeline B2B fintech dan menjalin hubungan dengan calon klien.",
    requirements: [
      "Fresh graduate semua jurusan, diutamakan Manajemen/Akuntansi",
      "Komunikatif dan target-oriented",
      "Pengalaman organisasi atau part-time sales menjadi nilai tambah",
    ],
    responsibilities: [
      "Mencari dan menghubungi calon klien B2B",
      "Menjadwalkan demo produk",
      "Mengelola pipeline di CRM",
    ],
    sourceName: "Dealls / LinkedIn",
    sourceUrl: "https://dealls.com",
    postedAt: new Date("2026-06-14"),
    closesAt: new Date("2026-08-20"),
    active: true,
  },
  {
    title: "Renewable Energy Engineer Trainee",
    company: "PLN",
    location: "Jakarta / Surabaya",
    workLocation: "onsite",
    type: "entry",
    category: "Energy & Sustainability",
    skills: ["Energy Systems", "Project Management", "AutoCAD", "ESG", "Data Analysis"],
    salaryRange: "Sesuai skema BUMN / trainee",
    description:
      "Program trainee energi terbarukan PLN untuk mendukung transisi energi nasional. Dibuka untuk fresh graduate teknik.",
    requirements: [
      "S1 Teknik Elektro, Teknik Mesin, atau Fisika Energi",
      "IPK minimal 3.00",
      "Bersedia ditempatkan di proyek energi terbarukan",
    ],
    responsibilities: [
      "Mendukung perencanaan dan operasional pembangkit EBT",
      "Mengumpulkan dan menganalisis data teknis lapangan",
      "Membuat laporan kemajuan proyek",
    ],
    sourceName: "JobStreet / LinkedIn",
    sourceUrl: "https://id.jobstreet.com/id/fresh-graduate-jobs",
    postedAt: new Date("2026-06-05"),
    closesAt: new Date("2026-07-20"),
    active: true,
  },
  {
    title: "Compliance Analyst — Crypto",
    company: "Pintu",
    location: "Jakarta / Remote",
    workLocation: "remote",
    type: "entry",
    category: "Web3 & Blockchain",
    skills: ["APU-PPT", "KYC/AML", "OJK/Bappebti Regulation", "Risk Assessment", "English"],
    salaryRange: "Rp 8.000.000 – 14.000.000/bulan",
    description:
      "Posisi entry-level untuk memastikan operasional aset kripto memenuhi regulasi APU-PPT dan standar compliance.",
    requirements: [
      "S1 Hukum, Akuntansi, Manajemen, atau Teknik Informatika",
      "Memahami dasar AML/CFT dan regulasi fintech/kripto",
      "Bahasa Inggris aktif",
    ],
    responsibilities: [
      "Mereview transaksi dan aktivitas pengguna mencurigakan",
      "Menyusun laporan compliance internal",
      "Mengikuti perkembangan regulasi OJK/Bappebti",
    ],
    sourceName: "web3.career / LinkedIn",
    sourceUrl: "https://web3.career/web3-jobs-indonesia",
    postedAt: new Date("2026-06-21"),
    closesAt: new Date("2026-08-15"),
    active: true,
  },
  {
    title: "Blockchain Operations Associate",
    company: "Tokocrypto",
    location: "Jakarta",
    workLocation: "hybrid",
    type: "entry",
    category: "Web3 & Blockchain",
    skills: ["On-chain Analysis", "Excel", "SQL", "Communication", "English"],
    salaryRange: "Rp 7.000.000 – 12.000.000/bulan",
    description:
      "Role operasional untuk mendukung tim produk dan operasional exchange aset kripto terbesar di Indonesia.",
    requirements: [
      "S1 semua jurusan, diutamakan Teknik Informatika/Manajemen/Akuntansi",
      "Memahami dasar blockchain dan wallet",
      "Analitis dan detail-oriented",
    ],
    responsibilities: [
      "Menganalisis data operasional harian exchange",
      "Mendukung proyek product growth dan campaign",
      "Membuat laporan mingguan untuk stakeholder",
    ],
    sourceName: "web3.career / LinkedIn",
    sourceUrl: "https://web3.career/web3-jobs-indonesia",
    postedAt: new Date("2026-06-19"),
    closesAt: new Date("2026-08-10"),
    active: true,
  },
  {
    title: "Smart Contract Developer (Junior)",
    company: "NOBI",
    location: "Remote",
    workLocation: "remote",
    type: "contract",
    category: "Web3 & Blockchain",
    skills: ["Solidity", "Ethereum", "Smart Contract Security", "DeFi", "Git"],
    salaryRange: "Project-based / USD-equivalent",
    description:
      "Kesempatan remote untuk developer yang ingin mendalami DeFi dan smart contract. Cocok untuk yang punya portofolio GitHub.",
    requirements: [
      "Pengalaman coding Solidity dan deploy di testnet",
      "Memahami konsep DeFi dan tokenomics dasar",
      "Portofolio smart contract di GitHub",
    ],
    responsibilities: [
      "Mengembangkan dan audit smart contract sederhana",
      "Membantu integrasi protocol DeFi",
      "Menulis dokumentasi teknis",
    ],
    sourceName: "web3.career / GitHub Jobs",
    sourceUrl: "https://web3.career/web3-jobs-indonesia",
    postedAt: new Date("2026-06-23"),
    closesAt: new Date("2026-08-30"),
    active: true,
  },
  {
    title: "Part-time Content Writer — Tech",
    company: "Kitalulus",
    location: "Remote",
    workLocation: "remote",
    type: "part-time",
    category: "Marketing",
    skills: ["Content Writing", "SEO", "Research", "Bahasa Indonesia", "Tech Literacy"],
    salaryRange: "Rp 1.500.000 – 4.000.000/bulan",
    description:
      "Freelance menulis artikel karier dan teknologi untuk platform edtech. Cocok untuk mahasiswa yang ingin belajar sambil menghasilkan portofolio.",
    requirements: [
      "Mahasiswa aktif semua jurusan",
      "Menulis dengan baik dalam Bahasa Indonesia",
      "Tertarik dengan topik karier dan teknologi",
    ],
    responsibilities: [
      "Menulis 2–4 artikel per minggu sesuai brief",
      "Melakukan riset sederhana tentang tren karier",
      "Mengikuti style guide platform",
    ],
    sourceName: "Kitalulus / Glints",
    sourceUrl: "https://www.kitalulus.com",
    postedAt: new Date("2026-06-24"),
    closesAt: new Date("2026-08-01"),
    active: true,
  },
  {
    title: "Data Entry & Operations Intern",
    company: "Ajaib",
    location: "Jakarta",
    workLocation: "hybrid",
    type: "internship",
    category: "Business",
    skills: ["Excel", "Google Sheets", "Attention to Detail", "Communication"],
    salaryRange: "Rp 1.200.000 – 2.500.000/bulan",
    description:
      "Magang operasional untuk mendukung tim back-office fintech investasi. Cocok untuk mahasiswa semester akhir yang ingin belajar industri fintech.",
    requirements: [
      "Mahasiswa semester 6+ semua jurusan",
      "Mahir Microsoft Excel / Google Sheets",
      "Detail-oriented dan dapat bekerja dalam tim",
    ],
    responsibilities: [
      "Memasukkan dan memvalidasi data operasional",
      "Membantu pembuatan laporan harian",
      "Koordinasi antar tim internal",
    ],
    sourceName: "Kalibrr / Glints",
    sourceUrl: "https://www.kalibrr.com",
    postedAt: new Date("2026-06-17"),
    closesAt: new Date("2026-07-30"),
    active: true,
  },
];
