import {
  LayoutDashboard as DashboardIcon,
  FolderOpen as WorkspaceIcon,
  CalendarDays as CalendarIcon,
  Bot as TutorIcon,
  PenTool as WritingIcon,
  Users as CollabIcon,
  GraduationCap as ExamIcon,
  BarChart3 as AnalyticsIcon,
  Bell as BellIcon,
  Sparkles as SparklesIcon,
  ChevronRight as ChevronIcon,
  BookOpen as BookIcon,
  Info as InfoIcon,
  UploadCloud as UploadIcon,
  Search as SearchIcon,
  PlayCircle as PlayIcon,
  Send as SendIcon,
  Share2 as ShareIcon,
  BrainCircuit as BrainIcon,
  AlignLeft as AlignLeftIcon,
  FileText as FileTextIcon,
  Mic as MicIcon,
  PauseCircle as PauseIcon,
  CheckCircle2 as CheckIcon,
  Plus as PlusIcon,
  MoreVertical as MoreIcon,
  Star as StarIcon,
  Shield as ShieldIcon,
  X as CloseIcon,
  Trash as TrashIcon,
  Users as UserIcon,
  Mail as MailIcon,
  Lock as LockIcon,
  User as UserProfileIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  ArrowRight as ArrowRightIcon,
  Globe as GlobeIcon
} from "lucide-react";

export {
  DashboardIcon,
  WorkspaceIcon,
  CalendarIcon,
  TutorIcon,
  WritingIcon,
  CollabIcon,
  ExamIcon,
  AnalyticsIcon,
  BellIcon,
  SparklesIcon,
  ChevronIcon,
  BookIcon,
  InfoIcon,
  UploadIcon,
  SearchIcon,
  PlayIcon,
  SendIcon,
  ShareIcon,
  BrainIcon,
  AlignLeftIcon,
  FileTextIcon,
  MicIcon,
  PauseIcon,
  CheckIcon,
  PlusIcon,
  MoreIcon,
  StarIcon,
  ShieldIcon,
  CloseIcon,
  TrashIcon,
  UserIcon
};
